---
- name: Create Projects directory
  file:
    group: "{{ user }}"
    owner: "{{ user }}"
    path: ~{{ user }}/Projects
    state: directory

- name: Copy profile pic
  copy:
    src: face
    dest: ~{{ user }}/.face
    owner: "{{ user }}"
    group: "{{ user }}"

- name: Make link
  file:
    src: ~{{ user }}/.face
    dest: ~{{ user }}/.face.icon
    state: link
    owner: "{{ user }}"
    group: "{{ user }}"

- name: Copy wallpaper
  copy:
    src: "{{ item }}"
    dest: ~{{ user }}/Pictures
    owner: "{{ user }}"
    group: "{{ user }}"
  with_fileglob:
    - wallpapers/*

- name: Copy script
  template:
    src: chgwall.sh.j2
    dest: /tmp/chgwall.sh
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0755
    
- name: Execute the script
  shell:
    /tmp/chgwall.sh
  become: yes
  become_user: "{{ user }}"

- name: Set Papirus-Dark icons theme
  shell: /usr/lib/plasma-changeicons Papirus-Dark
  async: 10
  poll: 0
  become: yes
  become_user: "{{ user }}"

- name: Change folders color
  shell: papirus-folders -C red --theme Papirus-Dark
  become: yes
  become_user: "{{ user }}"

- name: Remove the user aur_builder
  user:
    name: aur_builder
    state: absent
    remove: yes