---
- name: Install Latte
  pacman:
    name: latte-dock
  become: yes

- name: Start latte
  script: start.sh
  become: yes
  become_user: "{{ user }}"

- name: Init latte
  command: "{{ item }}"
  with_items:
    - sleep 5
    - killall latte-dock
  ignore_errors: yes

- name: Copy config
  copy:
    src: krovo.layout.latte
    dest: ~{{ user }}/
    owner: "{{ user }}"
    group: "{{ user }}"

- name: Change layout
  command: "{{ item }}"
  with_items:
    - kwriteconfig5 --file lattedockrc --group UniversalSettings \
      --key currentLayout "krovo"
    - kwriteconfig5 --file lattedockrc --group UniversalSettings \
      --key lastNonAssignedLayout "krovo"

- name: Start latte
  script: start.sh
  become: yes
  become_user: "{{ user }}"